### ISSUE TITLE
feat: add 'Scroll Back to top' button

### ISSUE THREAD

**Issue by Njoguu** [GDSCKCA2023-224/Postman-Students-KCA#12]
Add a 'Scroll back to top' button that allows users to easily scroll back to the top of the page.

**Comment by MehekFatima** [comment]
hi @Njoguu Could you please assign this issue to me?

**Comment by Njoguu** [comment]
Hello @MehekFatima. Yea, sure.

**Comment by MehekFatima** [comment]
thank you.
