### ISSUE TITLE
chore: change button text on hero

### ISSUE THREAD

**Issue by Njoguu** [GDSCKCA2023-224/Postman-Students-KCA#19]
Change the button that reads `Join the Postman Students Club` on the hero section to `Become a Postman Student Expert` and it should link to [this url](https://bit.ly/become-a-student-expert) and open it on a new tab.

**Comment by ShreyasSN** [comment]
Hai @Njoguu 
Could you please assign this to me? I would like to make improvements on this website

**Comment by Njoguu** [comment]
Hello @ShreyasSN this issue has already been worked on. Let me review your changes.
